# Generated by Django 4.1.7 on 2023-04-20 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='imagess')),
                ('staus', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('trend', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
            ],
        ),
        migrations.CreateModel(
            name='prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('product_images', models.ImageField(upload_to='imagess')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('orginal_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('staus', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('trend', models.BooleanField(default=False, help_text='0=default,1=Trending')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cata')),
            ],
        ),
    ]
